// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdlmwlqsexisiwokinqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkbG13bHFzZXhpc2l3b2tpbnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTg1OTMsImV4cCI6MjA2MDgzNDU5M30.1vF-ZcEr7WwC1HBbM0I-72iHVZ80Sa974yqdK8TXmmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);